CREATE TABLE [dbo].[Audit]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[EntityId] UNIQUEIDENTIFIER NULL,
    [AuditTime] DATETIME2 NOT NULL, 
    [ActionedBy] UNIQUEIDENTIFIER NOT NULL, 
    [Action] NVARCHAR(10) NOT NULL, 
    [Resource] NVARCHAR(256) NOT NULL, 
    [Before] NVARCHAR(MAX) NULL, 
    [After] NVARCHAR(MAX) NULL
    CONSTRAINT [FK_Audit_Member] FOREIGN KEY ([ActionedBy]) REFERENCES [Member]([Id])
)
